plugins {
    id 'com.android.application'
}

android {
    namespace 'gal.rodrigosambade.multimedia.localhostvideo'
    compileSdk 37

    defaultConfig {
        applicationId 'gal.rodrigosambade.multimedia.localhostvideo'
        minSdk 23
        targetSdk 37
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core:1.16.0'
    implementation 'com.google.android.material:material:1.12.0'

    testImplementation 'junit:junit:4.13.2'
}
